language: python
python:
    - '3.6'
    - '2.7'
install:
    - pip install 'numpy>=1.14'
    - pip install 'keras'
    - pip install 'opencv-python>=3.3.0'
    - pip install 'pillow'
    - pip install 'tensorflow'
    - pip install 'pytest-pep8'
    - pip install 'cython'
    - pip install 'matplotlib'
    - pip install 'h5py'
cache: pip
script:
    - py.test --pep8
